inherit_from:
  - ../.rubocop.yml
Metrics/BlockLength:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - describe
    - include
    - not_to
    - require
    - require_relative
    - to
Style/Send:
  Enabled: false
