#!/usr/bin/env ruby

# frozen_string_literal: true

require 'slop'
require_relative '../lib/release_assistant.rb'

options =
  Slop.parse do |o|
    o.banner = <<~BANNER

      Usage: release [options]

      Example:
        release
        release --type minor
        release -t patch
    BANNER

    ReleaseAssistant.define_slop_options(o)

    o.on('-v', '--version', 'print the version') do
      puts(ReleaseAssistant::VERSION)
      exit
    end

    o.on('-h', '--help', 'print this help information') do
      puts(o)
      exit
    end
  end

ReleaseAssistant.logger.level = Logger::DEBUG if options.debug?

ReleaseAssistant.new(options).run_release
